### PR TITLE
About modal

### PR DESCRIPTION
**Pull request by jlyon1**
@garoller and @kochman if you two have ideas about what content to put into the about modal, please comment them here or send them to me.

### CODE REVIEW

**Comment by kochman** [comment]
Awesome. Can we try showing/hiding the modal like in this example? https://vuejs.org/v2/examples/modal.html I think we should avoid using jQuery stuff if we can just do it with Vue.

I'll write up some more stuff to put in there. Also, the admin alert (if active) currently appears over the about window; I think it should go under. Additionally, the window/page should scroll if the content of the about window is taller than the browser viewport.

**Comment by jlyon1** [comment]
Should we put the scroll bar inside the white window? I don't necessarily have a preference but the dual scroll bar kind of has an odd look.

**Comment by kochman** [comment]
I think scrolling the whole modal container is fine (greater grabbable area than just inside the white box). More akin to scrolling through a document vs. a list.

**Comment by kochman** [comment]
I don't feel like writing any more at the moment, so I'm just going to merge this. We can always add stuff later.

**Pull request merged**
