### PR TITLE
Use Vue.JS's minified production code

### PR DESCRIPTION
**Pull request by JCBird1012**
Obviously, this is best practice, and probably improves performance somewhere along the way.

### CODE REVIEW

**Comment by jlyon1** [comment]
I think we should just host Vuejs (an JQuery) ourselves

**Comment by JCBird1012** [comment]
That's fine, but we should make sure that we're using the serving the production variant to users.

**Comment by kochman** [comment]
Yes, let's drop it in our static directory next to Leaflet. We should also pull jQuery in.

**Comment by jlyon1** [comment]
Closing due to inactivity, this issue is addressed in #107

**Pull request closed without merging**
