### PR TITLE
Add an indicator to show when the shuttle tracker is live

### PR DESCRIPTION
**Pull request by jlyon1**
Right now, the indicator displays disconnected when **_all_** ajax calls are  failing. Should it be when no data is received instead? Or when only one ajax call fails?

### CODE REVIEW

**Comment by kochman** [comment]
I think that the most sensible thing to do is consider it “live” if all of the calls are succeeding.

**Comment by kochman** [comment]
So this looks good, but I'm not sure that it solves the problem of indicating to the user that she doesn't have to refresh the page.

The old shuttle tracker had a "Last updated: 7:02:14 pm" thing in a corner of the map that always had the most recent update time. We could maybe try that approach? Another option could be to put the word "Live" in the circle (except it should probably be a rounded rectangle then).

We could also maybe detect when the page is reloaded frequently and show some kind of alert. Maybe something like https://stackoverflow.com/a/36444134. That alert system could also be used to prompt people to add the Shuttle Tracker to their home screens after they visit a couple of times.

**Comment by jlyon1** [comment]
@kochman Should the indicator disappear when API calls are failing or just stop updating the time? Currently it disappears when no updates are found, although i think i should make it change color or something, but not fully go away.

**Comment by kochman** [comment]
I like this. I think it could be white/more similar to the design of the header.

I think it should stay on screen if there are no updates, but the time will not change.

What if we did something that counts up, e.g. "Updated: 3 seconds ago?" Might be way too distracting.

**Comment by kochman** [comment]
@jlyon1 See http://momentjs.com. I use it in https://github.com/kochman/repostatus/blob/master/static/branch-card.js

**Comment by jlyon1** [comment]
@kochman so if we do use a count up approach, most of the time it will stay at "updated 3s ago" which would imply normal operation, I wouldn't be opposed to this, however, this means that during normal operation the counter will not be updating, which I feel like is more likely to cause people to refresh the page assuming its frozen.

**Comment by kochman** [comment]
Good point... so now I'm thinking about making the text say "Live" with a pulsating circle next to it (like used to be in the header). If there haven't been any updates in the last minute, it could change to a timestamp. (I'm just spitballing.)

**Comment by jlyon1** [comment]
@kochman hows this look?

**Comment by kochman** [comment]
Looks great! One thing is that the last updated time should be displayed as e.g. "1:03:02 pm" instead of "13:03:02," but we can fix that later.

**Pull request merged**
