### PR TITLE
TV Panel Scaffold

### PR DESCRIPTION
**Pull request by josephom12**
This PR deals with adding the TV panel's route at /tvpanel, a scaffold for the re-work of the display, and the wireframe in the assets folder.

### CODE REVIEW

**Comment by quuu** [comment]
This is not ready to review, the scaffold just has the text "TV PANEL", no reason to merge this in

Additionally, no need to add a route to the backend Go portion, should just be adding a vue component in the front-end for the TV panel...

**Comment by josephom12** [comment]
> Make the endpoint to be on the front-end, more can be explained if needed
> 
> Add more functionality before merging into master

I'll add more functionality to this PR according to the wireframe before requesting reviews again!

How do you make the end-point only on the frontend? @quuu

**Comment by quuu** [comment]
Alternatively, you could implement the features and THEN make the pull request

Look into the front-end folder of the code base, and look at how things like /settings and /schedules are implemented... thats where your TV-panel would sit

The back-end go routing is for pages like /vehicles, /routes, /updates... not the kind of information you want to be dispalying

**Comment by josephom12** [comment]
> Alternatively, you could implement the features and THEN make the pull request
> 
> Look into the front-end folder of the code base, and look at how things like /settings and /schedules are implemented... thats where your TV-panel would sit
> 
> The back-end go routing is for pages like /vehicles, /routes, /updates... not the kind of information you want to be dispalying

image

I think settings and schedules are implemented the same way but I might be missing something @quuu

**Comment by quuu** [comment]
> > Alternatively, you could implement the features and THEN make the pull request
> > Look into the front-end folder of the code base, and look at how things like /settings and /schedules are implemented... thats where your TV-panel would sit
> > The back-end go routing is for pages like /vehicles, /routes, /updates... not the kind of information you want to be dispalying
> 
> image
> 
> I think settings and schedules are implemented the same way but I might be missing something @quuu

Oops my bad, you're right, you just need that 1 line in the back-end to specify the routing to that page

**Pull request closed without merging**
